# Generated by Django 4.2.16 on 2024-11-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('median_income', models.FloatField()),
                ('population_density', models.FloatField()),
                ('education_level', models.CharField(choices=[('NO_EDUCATION', 'No Formal Education'), ('PRIMARY', 'Primary Education'), ('SECONDARY', 'Secondary Education'), ('COLLEGE', 'College'), ('POSTGRAD', 'Postgraduate')], default='SECONDARY', help_text='Dominant education level in the demographic.', max_length=15)),
                ('employment_rate', models.FloatField()),
                ('urban_rural', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailers', to='backend.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='backend.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='backend.retailer')),
            ],
        ),
    ]
